---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: imagedeploys.crd.whizzosoftware.com
spec:
  group: crd.whizzosoftware.com
  names:
    kind: ImageDeploy
    listKind: ImageDeployList
    plural: imagedeploys
    shortNames:
      - idp
    singular: imagedeploy
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deployment:
                  type: object
                  properties:
                    metadata:
                      type: object
                      properties:
                        name:
                          type: string
                        namespace:
                          type: string
                        labels:
                          type: object
                          additionalProperties:
                            type: string
                    spec:
                      type: object
                      properties:
                        replicas:
                          type: integer
                          minimum: 1
                          maximum: 10
                        selector:
                          type: object
                          properties:
                            matchLabels:
                              type: object
                              additionalProperties:
                                type: string
                        template:
                          type: object
                          properties:
                            metadata:
                              type: object
                              properties:
                                labels:
                                  type: object
                                  additionalProperties:
                                    type: string
                            spec:
                              type: object
                              properties:
                                containers:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      name:
                                        type: string
                                      image:
                                        type: string
                                      env:
                                        type: array
                                        items:
                                          type: object
                                          properties:
                                            name:
                                              type: string
                                            value:
                                              type: string
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kpush-controller
  namespace: kpush
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kpush-controller
rules:
  - apiGroups: ["extensions","apps"]
    resources:
      - deployments
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: 
    - build.pivotal.io
    resources:
      - images
    verbs:
      - get
      - list
      - watch
  - apiGroups: 
    - crd.whizzosoftware.com
    resources:
      - imagedeploys
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kpush-controller-binding
roleRef:
  kind: ClusterRole
  name: kpush-controller
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: kpush-controller
    namespace: kpush
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: kpush
  name: kpush
  namespace: kpush
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpack
  template:
    metadata:
      labels:
        app: kpack
    spec:
      serviceAccountName: kpush-controller
      containers:
      - name: kpush
        image: harbor.local.whizzosoftware.com/whizzo/kpush:latest
