apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: imagedeploys.crd.whizzosoftware.com
spec:
  group: crd.whizzosoftware.com
  names:
    kind: ImageDeploy
    listKind: ImageDeployList
    plural: imagedeploys
    shortNames:
      - idp
    singular: imagedeploy
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deployment:
                  type: object
                  properties:
                    metadata:
                      type: object
                      properties:
                        name:
                          type: string
                        namespace:
                          type: string
                        labels:
                          type: object
                          additionalProperties:
                            type: string
                    spec:
                      type: object
                      properties:
                        replicas:
                          type: integer
                          minimum: 1
                          maximum: 10
                        selector:
                          type: object
                          properties:
                            matchLabels:
                              type: object
                              additionalProperties:
                                type: string
                        template:
                          type: object
                          properties:
                            metadata:
                              type: object
                              properties:
                                labels:
                                  type: object
                                  additionalProperties:
                                    type: string
                            spec:
                              type: object
                              properties:
                                containers:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      name:
                                        type: string
                                      image:
                                        type: string
                                      env:
                                        type: array
                                        items:
                                          type: object
                                          properties:
                                            name:
                                              type: string
                                            value:
                                              type: string

